/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dongnao_jnitest_ExampleUnitTest */

#ifndef _Included_com_dongnao_jnitest_ExampleUnitTest
#define _Included_com_dongnao_jnitest_ExampleUnitTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dongnao_jnitest_ExampleUnitTest
 * Method:    test
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dongnao_jnitest_ExampleUnitTest_test
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
